/* ================= CATEGORY STRUCTURE ================= */

export const categories = [
  { name: "Foam", value: "foam", subcategories: ["memory", "orthopedic"] },
  { name: "Spring", value: "spring", subcategories: ["pocket", "bonnell"] },
  { name: "Hybrid", value: "hybrid", subcategories: ["luxury", "cooling"] },
  {
    name: "Accessories",
    value: "accessories",
    subcategories: ["pillow", "protector"],
  },
];

/* ================= PRODUCTS ================= */
export const products = [
  {
    id: 1,
    slug: "memory-foam-deluxe",
    name: "Memory Foam Deluxe",
    description: "Pressure-relief memory foam with breathable comfort.",
    price: 115000,
    oldPrice: null,
    discount: 0,
    category: "foam",
    subcategory: "memory",
    image: "/images/mattresses.png",
    available: true,
  },
  {
    id: 2,
    slug: "orthopedic-foam-pro",
    name: "Orthopedic Foam Pro",
    description: "Firm support engineered for spinal alignment.",
    price: 128000,
    oldPrice: null,
    discount: 0,
    category: "foam",
    subcategory: "orthopedic",
    image: "/images/mattresses.png",
    available: true,
  },
  {
    id: 3,
    slug: "pocket-spring-elite",
    name: "Pocket Spring Elite",
    description: "Individual pocket coils for motion isolation.",
    price: 149000,
    oldPrice: 179000,
    discount: 17,
    category: "spring",
    subcategory: "pocket",
    image: "/images/mattresses.png",
    available: true,
  },
  {
    id: 4,
    slug: "bonnell-classic",
    name: "Bonnell Classic",
    description: "Durable traditional spring structure.",
    price: 99000,
    oldPrice: null,
    discount: 0,
    category: "spring",
    subcategory: "bonnell",
    image: "/images/mattresses.png",
    available: false,
  },
  {
    id: 5,
    slug: "luxury-hybrid-max",
    name: "Luxury Hybrid Max",
    description: "Foam and coils combined for premium balance.",
    price: 175000,
    oldPrice: null,
    discount: 0,
    category: "hybrid",
    subcategory: "luxury",
    image: "/images/mattresses.png",
    available: true,
  },
  {
    id: 6,
    slug: "cooling-hybrid-breeze",
    name: "Cooling Hybrid Breeze",
    description: "Temperature-regulated hybrid comfort.",
    price: 162000,
    oldPrice: null,
    discount: 0,
    category: "hybrid",
    subcategory: "cooling",
    image: "/images/mattresses.png",
    available: true,
  },
  {
    id: 7,
    slug: "luxury-pillow",
    name: "Luxury Pillow",
    description: "Ergonomic support pillow.",
    price: 9000,
    oldPrice: null,
    discount: 0,
    category: "accessories",
    subcategory: "pillow",
    image: "/images/mattresses.png",
    available: true,
  },
  {
    id: 8,
    slug: "mattress-protector",
    name: "Mattress Protector",
    description: "Waterproof breathable protection layer.",
    price: 6500,
    oldPrice: null,
    discount: 0,
    category: "accessories",
    subcategory: "protector",
    image: "/images/mattresses.png",
    available: true,
  },
];

export const itemsPerPage = 6;
